apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-read-config
rules:
- apiGroups: [""]
  resources: ["configmaps","secrets"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-read-config
subjects:
- kind: ServiceAccount
  name: api-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-read-config