deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    enabled: false
  extraVolumes:
    - name: loki-storage
      emptyDir: {}
  extraVolumeMounts:
    - name: loki-storage
      mountPath: /var/loki

backend: { replicas: 0 }
read:    { replicas: 0 }
write:   { replicas: 0 }

chunksCache:
  enabled: false
resultsCache:
  enabled: false

loki:
  auth_enabled: false
  server:
    http_listen_port: 3100
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory:  /var/loki/rules
  schemaConfig:
    configs:
      - from: "2025-01-01"
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  limits_config:
    retention_period: 168h
    allow_structured_metadata: false

service:
  type: ClusterIP