apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 15.3.2
    helm:
      releaseName: rabbitmq
      values: |
        fullnameOverride: rabbitmq

        auth:
          username: appuser
          password: apppassword

        persistence:
          enabled: false

        # --- ÖNEMLİ: GHCR'ı sıfırla, docker hub'a zorla
        global:
          imageRegistry: ""              # ghcr kalıntısını sıfırlar

        image:
          registry: docker.io
          repository: bitnami/rabbitmq
          tag: "4.0.6"                   # mevcut, public tag

        service:
          type: ClusterIP

        ingress:
          enabled: true
          ingressClassName: alb
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
          path: /
          pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
