apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 8.5.11
    helm:
      values: |
        adminUser: admin
        adminPassword: admin123
        service:
          type: ClusterIP
        sidecar:
          datasources:
            enabled: true
        ingress:
          enabled: true
          ingressClassName: alb
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
          hosts:
            - grafana.local   # DNS şart değil; ALB DNS ile da erişebilirsin
          path: /
          pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]