apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 15.3.2
    helm:
      releaseName: rabbitmq
      values: |
        fullnameOverride: rabbitmq

        auth:
          username: appuser
          password: apppassword

        persistence:
          enabled: false

        global:
          imageRegistry: public.ecr.aws
          security:
            allowInsecureImages: true

        image:
          registry: public.ecr.aws
          repository: bitnami/rabbitmq
          tag: "4.0.6-debian-12-r3"

        # UI açık ama sadece cluster içi; dışa ALB yok
        service:
          type: ClusterIP

        extraConfiguration: |
          management.tcp.port = 15672
          management.tcp.ip   = 0.0.0.0
          loopback_users.guest = false

        # Bitnami default probe’ları açık; startup’ı biraz daha toleranslı yap
        startupProbe:
          enabled: true
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 12
        readinessProbe:
          enabled: true
        livenessProbe:
          enabled: true

        # ALB/Ingress yok
        ingress:
          enabled: false

        # İki ayrı iç servis (AMQP) – uygulamalar bunlardan birini kullanabilir
        extraDeploy:
          - |
            apiVersion: v1
            kind: Service
            metadata:
              name: rabbitmq-svc-1
              labels:
                app.kubernetes.io/name: rabbitmq
                app.kubernetes.io/instance: rabbitmq
            spec:
              type: ClusterIP
              selector:
                app.kubernetes.io/name: rabbitmq
                app.kubernetes.io/instance: rabbitmq
              ports:
                - name: amqp
                  port: 5672
                  targetPort: amqp
          - |
            apiVersion: v1
            kind: Service
            metadata:
              name: rabbitmq-svc-2
              labels:
                app.kubernetes.io/name: rabbitmq
                app.kubernetes.io/instance: rabbitmq
            spec:
              type: ClusterIP
              selector:
                app.kubernetes.io/name: rabbitmq
                app.kubernetes.io/instance: rabbitmq
              ports:
                - name: amqp
                  port: 5672
                  targetPort: amqp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
