apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 15.3.2
    helm:
      releaseName: rabbitmq
      values: |
        # ---- İsimleri sabitle
        fullnameOverride: rabbitmq

        # ---- Tüm imajları GHCR'den çek
        global:
          imageRegistry: ghcr.io

        # ---- Ana container imajını da net sabitle
        image:
          registry: ghcr.io
          repository: bitnami/rabbitmq
          tag: 4.0.6-debian-12-r3
          pullPolicy: IfNotPresent

        # ---- Yetkilendirme
        auth:
          username: appuser
          password: apppassword

        # ---- Servis
        service:
          type: ClusterIP

        # ---- Demo için kalıcı disk kapalı
        persistence:
          enabled: false

        # ---- Ek init container (volumePermissions) kapalı kalsın
        volumePermissions:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
