apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 15.3.2
    helm:
      releaseName: rabbitmq
      values: |
        fullnameOverride: rabbitmq          # Servis adı kesin "rabbitmq" olsun
        auth:
          username: appuser
          password: apppassword
        service:
          type: ClusterIP
        persistence:
          enabled: false
        volumePermissions:                  # Init:ImagePullBackOff sebebini kapatıyoruz
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      # BUNU ekleyince immutable alan değişikliklerinde sil-yarat yapar:
      - Replace=true
