apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alb-controller-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.8.2
    helm:
      values: |
        clusterName: ${EKS_CLUSTER_NAME}
        region: ${AWS_REGION}
        vpcId: ${VPC_ID}
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: "${ALB_CONTROLLER_ROLE_ARN}"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]