apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 15.3.2
    helm:
      releaseName: rabbitmq
      values: |
        # İsimler sabit
        fullnameOverride: rabbitmq

        # Kimlik
        auth:
          username: appuser
          password: apppassword

        # Disk kapalı (demo)
        persistence:
          enabled: false

        # ---- ÖNEMLİ: docker hub + var olan basit tag ----
        image:
          registry: docker.io
          repository: bitnami/rabbitmq
          tag: "4.0.6"

        # Servis
        service:
          type: ClusterIP

        # Ingress (ALB), hostsiz — ALB kendi DNS üretir
        ingress:
          enabled: true
          ingressClassName: alb
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
            alb.ingress.kubernetes.io/healthcheck-path: /
          path: /
          pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
