apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 15.3.2
    helm:
      releaseName: rabbitmq
      values: |
        fullnameOverride: rabbitmq

        auth:
          username: appuser
          password: apppassword

        persistence:
          enabled: false

        global:
          imageRegistry: public.ecr.aws
          security:
            allowInsecureImages: true

        image:
          registry: public.ecr.aws
          repository: bitnami/rabbitmq
          tag: "4.0.6-debian-12-r3"

        # UI/Ingress yok; içten kullanılacak
        service:
          type: ClusterIP

        # UI portu yine açık, ama sadece cluster içinden erişilir
        extraConfiguration: |
          management.tcp.port = 15672
          management.tcp.ip   = 0.0.0.0
          loopback_users.guest = false

        # (İstersen kalabilir) TCP custom probe'lar
        customStartupProbe:
          tcpSocket: { port: 15672 }
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 60
        customReadinessProbe:
          tcpSocket: { port: 15672 }
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 60
        customLivenessProbe:
          tcpSocket: { port: 15672 }
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 8

        ingress:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
