apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 15.3.2
    helm:
      releaseName: rabbitmq
      values: |
        # Servis/PVC isimleri sabit
        fullnameOverride: rabbitmq

        # Kimlik bilgileri (demo)
        auth:
          username: appuser
          password: apppassword

        # Servis tipi
        service:
          type: ClusterIP

        # Demo: disk kalıcı değil
        persistence:
          enabled: false

        # --- ÖNEMLİ: GHCR kullan ve imaj doğrulamasını aç ---
        global:
          imageRegistry: ghcr.io
          security:
            allowInsecureImages: true

        # Ana RabbitMQ imajını net sabitle
        image:
          registry: ghcr.io
          repository: bitnami/rabbitmq
          tag: 4.0.6-debian-12-r3
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
