apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 15.3.2
    helm:
      releaseName: rabbitmq
      values: |
        # --- Servis/PVC adları sabit kalsın
        fullnameOverride: rabbitmq

        # --- Auth
        auth:
          username: appuser
          password: apppassword

        # --- Servis tipi
        service:
          type: ClusterIP

        # --- Persist kapalı (demo)
        persistence:
          enabled: false

        # --- Tüm imajları GHCR'den çek
        global:
          imageRegistry: ghcr.io

        # --- Ana RabbitMQ imajını da net sabitle
        image:
          registry: ghcr.io
          repository: bitnami/rabbitmq
          tag: 4.0.6-debian-12-r3

  destination:
    server: https://kubernetes.default.svc
    namespace: messaging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
