apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 15.3.2
    helm:
      releaseName: rabbitmq
      values: |
        fullnameOverride: rabbitmq

        auth:
          username: appuser
          password: apppassword

        persistence:
          enabled: false

        global:
          imageRegistry: public.ecr.aws
          security:
            allowInsecureImages: true

        image:
          registry: public.ecr.aws
          repository: bitnami/rabbitmq
          tag: "4.0.6-debian-12-r3"

        # UI yok; yalnızca iç kullanıma açık servis
        service:
          type: ClusterIP

        # Management plugin açık (iç ağ), ama probe'ları CHART'ın default'ına bırakıyoruz
        extraConfiguration: |
          management.tcp.port = 15672
          management.tcp.ip   = 0.0.0.0
          loopback_users.guest = false

        # ÖNEMLİ: custom*Probe'ları tamamen kaldırıyoruz (describe'da görülen TCP 15672'ler gitsin)
        startupProbe:
          enabled: true
        readinessProbe:
          enabled: true
        livenessProbe:
          enabled: true

        ingress:
          enabled: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
