apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: rabbitmq
    targetRevision: 15.3.2
    helm:
      values: |
        # ---- İsimleri sabit tut (service adı: rabbitmq)
        fullnameOverride: rabbitmq

        # ---- Demo kullanıcıları
        auth:
          username: appuser
          password: apppassword

        # ---- Servis tipi (ALB Ingress, ClusterIP servise yönlenir)
        service:
          type: ClusterIP

        # ---- Demo: disk kalıcı değil
        persistence:
          enabled: false

        # ---- Yönetim UI (15672) için Ingress (AWS ALB)
        ingress:
          enabled: true
          ingressClassName: alb
          hostname: rabbitmq.dev.local        # Kendi domainin varsa onu yaz
          path: /
          pathType: Prefix
          servicePort: manager                # 15672 (management UI)
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/target-type: ip
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
  destination:
    server: https://kubernetes.default.svc
    namespace: messaging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
