apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 6.6.5
    helm:
      values: |
        deploymentMode: SingleBinary
        singleBinary:
          replicas: 1

        global: { storageClass: gp3-csi }

        loki:
          structuredConfig:
            auth_enabled: false
            server: { http_listen_port: 3100 }
            common: { replication_factor: 1 }
            storage_config:
              aws:
                s3: "s3://${LOKI_BUCKET_NAME}"
                region: "${AWS_REGION}"
                s3forcepathstyle: true
            schema_config:
              configs:
                - from: "2025-01-01"
                  store: tsdb
                  object_store: s3
                  schema: v13
                  index: { prefix: loki_index_, period: 24h }

          storage:
            type: s3
            bucketNames:
              chunks: "${LOKI_BUCKET_NAME}"
              ruler:  "${LOKI_BUCKET_NAME}"
              admin:  "${LOKI_BUCKET_NAME}"

        gateway: { enabled: true }
        chunksCache:  { enabled: false }
        resultsCache: { enabled: false }
        ruler:        { enabled: false }
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]