apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: promtail
    targetRevision: 6.15.5
    helm:
      values: |
        config:
          clients:
            - url: http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push
          snippets:
            pipelineStages:
              - cri: {}
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]