apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: logging
  labels: { grafana_datasource: "1" }
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.logging.svc.cluster.local
        isDefault: true